events {
    worker_connections 2048;
}

http {
    upstream url_shortener_cluster {
        least_conn;
        server app-1:8080 max_fails=3 fail_timeout=10s;
        server app-2:8080 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://url_shortener_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Fast timeout for redirect paths
            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;
        }
    }
}
